### PR TITLE
:sunrise_over_mountains: Tidy up middleware tests

### PR DESCRIPTION
**Pull request by neilbmclaughlin**
The only bit of the middleware which is not tested now is the render functionality. There are some posts around about testing the values passed to res.render (this is the approach taken on the betahealth project https://github.com/nhsalpha/betahealth/blob/develop/test/unit/controllers/index.test.js) but I'm not sure about the value of them given we have server tests. Any thoughts?

Also, now that we have good error handling I've removed the console.log statements which negates the need for #87. I do think we need to add logging of errors but that is a separate piece of work and should probably go in the error handling middleware.

I'd anticipated moving on the looking at the server tests next and perhaps adding logging as part of that.

### CODE REVIEW

**Comment by neilbmclaughlin** [comment]
Also, there is a lot of commonality between getGpDetails and getGpOpeningTimes which I think could be refactored to separate out the bit which change from the bits which don't.

**Comment by st3v3nhunt** [comment]
I'd agree with the limited use of that type of test and be inclined to not have them seen as there are full stack tests that could be doing this. If there was a bunch of logic in the view (which obvs would be a problem that should be fixed in the first instance) they might be useful but as this shouldn't happen I think they have very limited use indeed.

**Comment by st3v3nhunt** [comment]
Why has `statusCode` usurped `status`?

**Comment by neilbmclaughlin** [comment]
`status` changed to `statusCode` to be consistent with the naming on http.response.

**Pull request merged**
