### PR TITLE
:bar_chart: Add Google analytics

### PR DESCRIPTION
**Pull request by neilbmclaughlin**
Added google analytics to master layout to start collecting stats
on usage. The tool may change so used a js file rather than placing
the js directly in the template.

### CODE REVIEW

**Comment by st3v3nhunt** [comment]
Is this OK to wait until #9 has been merged so it will go through CI?

**Comment by neilbmclaughlin** [comment]
@st3v3nhunt pull request #9 done so happy for this to go if you are.

**Comment by st3v3nhunt** [comment]
Can you rebase against master to bring in `.travis.yml` please?

**Comment by neilbmclaughlin** [comment]
Messed up the rebase (should have done it using the interactive option -i) so created a new branch and pull request.

**Pull request closed without merging**
