### PR TITLE
:feet: Add WebTrends tracking

### PR DESCRIPTION
**Pull request by neilbmclaughlin**
Opted to use the loader config as it more closely matches the approach adopted by Goggle Analytics and the other option seemed to be a noscript option. Need to check with Michael/Kenny if this is correct.

Adding WT seems to add 200ms to load time (300 ms -> 500 ms)

Timings on my machine:
No analytics: ~330 ms
GA: ~330 ms
GA + WT: ~500 ms

Including webtrends readme.txt for completeness

---

Webtrends Tag Readme File
Tag Builder Version: 4.1.3.5
Archive: Webtrends-10.4.0-Site.zip
Created: 4/21/2016 7:27:54 AM
# 
# CONTENTS
1. webtrends.html
   Inline HTML portion of the Webtrends tag.
2. webtrends.load.html
   Inline HTML portion of the Webtrends tag that can be used to dynamically load
   the Webtrends tag.
3. webtrends.js
   External JavaScript portion of the core Webtrends tag.
4. webtrends.min.js
   External JavaScript portion of the core Webtrends tag in minified form.
5. webtrends.load.js
   External JavaScript file that can be used to dynamically load the Webtrends tag.
# 
# DEPLOYING THE TAG BUILDER TAG

There are two ways to deploy tag.  Both ways are functionally equivalent.  The
differences lie in how you modify your web content to include the tag, and where
tag configuration information resides.
1. Loader Configuration - This approach minimizes changes to your web content
   because you simply add a single <script> block.  Two external JavaScript files
   are used, one for tag configuration, the other for core tag functionality.
   
   Your Content  ->  Tag Configuration JS  ->  Core Tag JS
   (.html)           (webtrends.load.js)       (webtrends.min.js)
2. Inline Configuration - This approach places tag configuration directly inside
   your web content.  A single external JavaScript file is used to provide core tag
   functionality.
   
   Your Content  ->  Core Tag JS
   (.html)           (webtrends.min.js)
# 
# LOADER CONFIGURATION STEPS
1. Save the following files in a common JavaScript location on your web server:
   webtrends.load.js, webtrends.min.js
2. Edit the following files and modify the path referenced so that agrees with
   location from Step 1:
   webtrends.load.html, webtrends.load.js
3. Paste the contents of webtrends.load.html on every page in your web site.
   To avoid logging hits to pages that do not load completely, and to
   ensure best performance, paste this code inside the <head> section
   of your web page.
# 
# INLINE CONFIGURATION STEPS
1. Save the webtrends.min.js file in a common JavaScript location on your web
   server.
2. Edit the webtrends.html file and modify the path referenced so that it
   agrees with location from Step 1.
3. Paste the contents of webtrends.html on every page in your web site.
   To avoid logging hits to pages that do not load completely, and to
   ensure best performance, paste this code inside the <head> section
   of your web page.

### CODE REVIEW

**Comment by neilbmclaughlin** [comment]
CodeClimate is not using .eslintignore

**Comment by neilbmclaughlin** [comment]
Viewed activity in Web Trends:

https://analytics.webtrends.com/analytics/spaces/151371/profiles/98204/reports/oOEWQj3sUo6#%7B%22report%22%3A%7B%22displayLength%22%3A25%2C%22displayStart%22%3A0%2C%22filter%22%3A%22%22%2C%22fullScreen%22%3Afalse%2C%22showChart%22%3Afalse%2C%22sortcol%22%3A1%2C%22sortdir%22%3A%22desc%22%2C%22viewMode%22%3A%22bar%22%7D%2C%22report-oOEWQj3sUo6%22%3A%5B%5D%7D

**Comment by st3v3nhunt** [comment]
Does the non-minified version of the file need to be checked in? bitHound is failing because of this and as that is a required pass it is currently unable to be merged.

**Comment by neilbmclaughlin** [comment]
Good spot - removed the non-minified version.

**Comment by st3v3nhunt** [comment]
I think it might be a good idea to add the `.codeclimate.yml` file to prevent it from failing. I've tested it works ok in PR #47. What do you reckon? I'd rather not add more and more configs to the code but this seems a reasonable thing to do until we decide which is the best code analysis tool.

**Comment by neilbmclaughlin** [comment]
Agreed & done after some fun and games when switching to ssh authentication.

**Comment by st3v3nhunt** [comment]
We need to get the code coverage up - it's annoying me seeing the red crosses!

**Pull request merged**
